### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Brusura** [DrBeef/Doom3Quest#1]
I am running on quest 2 ,  I am trying to change language to Italian, but those files get reverted to english every time

quest2_default.cfg
doom3quest.cfg

Thanks

**Comment by Brusura** [comment]
I managed to change it to italian.

Doom3Quest v1.1.1

1) Renamed all Z pak to 300 , 301 etc.. and copy them in the base folder with other .pak
2) Change english to italian in doom3quest.cfg

PS: old save in english make app crash, you have to start a new game

**Comment by fiocco10** [comment]
Can you add french too ? please, thank you.
