### ISSUE TITLE
Two handed weapon grip on pc mod

### ISSUE THREAD

**Issue by djsolidsnake86** [DrBeef/Doom3Quest#12]
Hi Dr Beef, can you add Two Handed Weapons grip on this pc mod please?
https://github.com/NPi2Loup/DOOM-3-BFG-VR/releases

i love you quest port, but me and many other user prefer play the pc version that has a better graphics

**Comment by baggyg** [comment]
You should contact the mod creator of the PC version for this. They should be able to see our code and bring it across relatively easy. Nothing against your choice of platform, we just don't get involved with back-porting to PCVR.
