### ISSUE TITLE
Ability to change control binds? Or provide touch controller > keyboard mapping

### ISSUE THREAD

**Issue by VuthMuul** [DrBeef/Doom3Quest#13]
Is it possible to rebind controls?
I found a doom3quest.cfg file that appears to have the bindings but it's all using keyboard buttons.
Is it possible to provide info on how the touch controller buttons were mapped to the keyboard?
Then if you're adventurous the controls can be manually swapped around at least.

**Comment by baggyg** [comment]
Check out this file. It shows what is bound to what. However you should be aware some buttons are directly bound to the impulse code and don't have the keyboard bind middleman (so you can't change these directly).
