### ISSUE TITLE
[Request] Dynamic shadows and question about sikkmod

### ISSUE THREAD

**Issue by NoUserNameForYou** [DrBeef/Doom3Quest#15]
Hello, I can't thank you enough for your valuable work DrBeef!

I have a question about dynamic shadows. I'm on Q2 and I'm willing to play the game at 1024x1024 resolution at 60hz with high foveated rendering options selected in Quest game optimizer. I don't care about the jaggies, I just tried and 1024 res is bareable for me.

I really would like to request you to either make a build or a drop in config mod to enable dynamic shadows for me. I really don't care if there are glitches, if shadows render only through one eye and flicker and drop performance. It takes me out of immersion, could you please be kind enough to provide that mod/build if it's not too much of a hassle?

Question about the sikkmod: Any possiblity this would work? I'm eyeing for SSAO tbh.

**Comment by baggyg** [comment]
Hi, I'm looking into reinstating these as part of my work on Quake 4. If I get it going then we'll backport in Doom 3. If only so people can try. Performance is rough though so I wouldn't expect 60fps even at 1024p. Maybe Quest 3 might do a better job

**Comment by baggyg** [comment]
RE; sikkmod. That's a separate DLL and I don't think the code is public, so its not going to work on standalone I am afraid.

**Comment by NoUserNameForYou** [comment]
Thank you for your efforts and answers. My fingers are crossed, I usually play skyrim pc vr with 40fps/80ssw through virtual desktop so I'm acclimated to low fps.

**Comment by NoUserNameForYou** [comment]
Hello @baggyg ! 

Are you planning to do dynamic shadows for Quake 4 and Doom 3 for Quest 3?

**Comment by baggyg** [comment]
Both games already have them!

**Comment by NoUserNameForYou** [comment]
Thank you!
