### ISSUE TITLE
GUI Interaction Weapon

### ISSUE THREAD

**Issue by alexbogun** [DrBeef/Doom3Quest#16]
Thanks for an amazing port!
I have a couple of issues/questions:

1) Maybe it is a user error, but when I set GUI interaction to weapon, I am unable to interact with PDA, it seems it defaults to gaze-based, but I am unable to click anything. Would it be possible to either set PDA interaction to weapon base as well or expose the setting to set PDA interaction separately (e.g. weapon based in the world and touch-based for PDA)?

2) Almost certainly it is just me, but I am not able to see the difference between MSAA 1x and 4x at all, moreover, it looks like there is no AA whatsoever. Is it the same on your end? I am using Quest 3.

Thank you!

**Comment by baggyg** [comment]
MSAA may require a restart. 

Defunkt is working on some changes to all interactions, so expect more option and fixed things when that releases soon.

**Comment by alexbogun** [comment]
Thanks for the quick reply. 
Indeed MSAA requires restart, 4 does look much better than 1.

Just a quick unrelated question: is there an option to disable flashlight timeout, or change it?
