### ISSUE TITLE
Language selection menu

### ISSUE THREAD

**Issue by Darknior** [DrBeef/Doom3Quest#2]
Hi
Thanks for your hard work, i love so much :) 

Is it possible ta have in the game menu a language selection option ?
Yes we can do it in the configuration file and change english to french if we have the good files. 
But it will be easier for users if they can do it in menu ...

Thanks a lot

**Comment by fiocco10** [comment]
Hello, i change the game english to french but i see the menu "system" is empty, why ?

**Comment by baggyg** [comment]
I've put this in the latest hotfix. Should be released as soon as it has been internally tested

**Comment by Darknior** [comment]
ok thanks a lot, i will close the issue when release, if some other have the same question in mind ...

**Comment by baggyg** [comment]
This is now released so closing this thread
